### ISSUE TITLE
E:local variable 'r' referenced before assignmen

### ISSUE THREAD

**Issue by vaibhavdost** [T-Dynamos/IgFreak#1]
I am getting this error after it tries 3 passwords

**Comment by T-Dynamos** [comment]
This project isn't having such great motivation to upgrade , but i will still try

**Comment by T-Dynamos** [comment]
> I am getting this error after it tries 3 passwords

I am unable to reproduce the error
Its working
![img](https://user-images.githubusercontent.com/68729523/182131870-7aec9eee-7ede-41b9-bf7f-ed857a5a6af9.jpg)
